language: swift

osx_image: xcode9

cache:
  - cocoapods

branches:
  only:
    - master

env:
  - LC_TYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - gem install cocoapods
  - pod repo update

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Chika' -t 85d11916-33fd-4ec9-baa4-b5cd073b53c8

before_script:
  - cp CI/Dummy_GoogleService-Info.plist GoogleService-Info.plist

script:
  - set -o pipefail
  - xcodebuild build test -workspace Chika.xcworkspace -scheme Chika -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone SE"
