language: swift

osx_image: xcode9

cache:
  - cocoapods

branches:
  only:
    - master

env:
  - LC_TYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - rvm install ruby2.0.0
  - gem install cocoapods
  - gem install xcpretty -N

script:
  - set -o pipefail
  - xcodebuild build test -workspace Chika.xcworkspace -scheme Chika -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone SE" | xcpretty -c
